---
title: "TP1"
output: html_document
date: "2024-09-11"
---

Exercice 1 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
X <- runif(10000)
X <- 5*(X<=0.4) + 6*(0.4<X & X<=0.6) + 7*(0.6<X & X<=0.9) + 8*(0.9<X)
```

```{r}
Y <- table(X)
V <- c(0.4,0.2,0.3,0.1)

barplot(Y/length(X))
barplot(V, col = 'red')
```
Exercice 2 

1)
```{r}
n <- 10000
Y <- runif(n)
X <- -1/2 * log(1-Y)
hist(X, breaks = 100,freq = FALSE,col='red')
qqplot(X,rexp(n,2))
```
2)
```{r}
lambda <- 1.5
n <- 10000
Sn <- numeric(n)

for (i in 1:n){
  p <- 1
  X <- -1/lambda * log(1- runif(10))
  Sn[i] <- sum(X)
}
hist(Sn, breaks = 50,freq = FALSE)
curve(dgamma(x,shape = 10,rate = lambda),add = TRUE, col = "red")
```
```{r}
lambda <- 4
n <- 10000
Sn <- numeric(n)

for (i in (1:n)){
  p <- 1
  X <- -1/lambda * log(1- runif(1))
  while(X<=1){
    p <- p+1
    X <- X - 1/lambda * log(1- runif(1))
  }
  Sn[i] <- p
  p <- 1
}
hist(Sn,freq = FALSE)
```


Exercice 3 

```{r}
BM <- function(n){
  U1 = runif(n)
  U2 = runif(n)
  return(c(sqrt(-2*log(U1)) * cos(2*pi*U2),sqrt(-2*log(U1)) * sin(2*pi*U2)))
}

hist(BM(10000), freq = FALSE, breaks = 100) 
curve(dnorm(x),add = TRUE, col = 'red')
```

Exercice 5:

```{r}
n <- 1:1110

W0 <- 0
Brownian <- function(i) {
 return( (i >= 1 & i <= 100)*(i/100) + (i>=101 & i<=110)*(1 + (i-100)/10) + (i>=111 & i<=1110)*(2 + (i-110)/1000) ) 
}

t <- Brownian(n)
W <- W0 + sqrt(t) * rnorm(1110)
plot(t,W,type= "o")
```
Exercice 6:

```{r}
n = 10000
f <- function(x){
  return(2/pi * sqrt(1-x**2) * (-1<=x & x <= 1))
}

M <- 4/pi
g <- function(x){
  return(1/2 * (-1<=x & x <= 1))
}

Y = NULL
while (length(Y) < n) {
  U <- runif(n)
  X <- runif(n,-1,1)
  fx <- f(X)
  gx <- g(X)
  Y <-append( Y , X[U <= fx/(M * gx)])
}

t <- seq(-1,1,1/n)


hist(Y, freq = FALSE)
lines(t,f(t),col="red")
```

Exercice 7 :

```{r}
n = 10000
f <- function(x,y){
  return(1/pi * (x**2+y**2 <= 1))
}

M <- 4/pi
g <- function(x,y){
  return(1/4 * (-1<=x & x <= 1) * (-1<=y & y <= 1))
}

x <- NULL
y <- NULL

while (length(x) < n) {
  U <- runif(1)
  X <- runif(1,-1,1)
  Y <- runif(1,-1,1)
  fx <- f(X,Y)
  gx <- g(X,Y)
  x <-append(x , X[U <= fx/(M * gx)])
  y <-append(y , Y[U <= fx/(M * gx)])
}

plot(x,y)
```


Exercice 8:

```{r}

f <- function(x,b,mean,sd){
  return(
    1/(sqrt(2*pi*sd**2)*pnorm((mean - b)/sd))*exp(-1/2 * (mean - x)^2/sd**2) * (x>=b))
}

n <- 10000
mean <- 0
sd <- 2
b <- 2

M <- 1/pnorm((mean - b)/sd)
g <- function(x,mean,sd){
  return(1/sqrt(2*pi*sd**2)*exp(-1/2 * (mean - x)^2/sd**2))
}

x = numeric(0)
while (length(x) < n) {
  U <- runif(1)
  X <- rnorm(1,mean,b)
  x <- append(x, X[U <= (f(X, b, mean, sd) / (M * g(X, mean, sd)))])
}

t <- seq(b,8,0.01)

hist(x, freq = FALSE, breaks = 50)
lines(t, f(t, b, mean, sd), col=rgb(180/255, 50/255, 213/255))
```

```{r}

f2 <- function(x,b,lam){
  return(-lam * exp(-lam*(x-b))*(x>=b))
}

n <- 10000
mean <- 0
sd <- 2
b <- 2
lam <- 2

M2 <- exp(lam*b)
g2 <- function(x,b,lam){
  return(rexp(lam)+b)
}

x = numeric(0)
while (length(x) < n) {
  U <- runif(1)
  X <- rnorm(1,mean,b)
  x <- append(x, X[U <= (f2(X, b, lam) / (M2 * g2(X, b, lam)))])
}

t <- seq(b,8,0.01)

hist(x, freq = FALSE, breaks = 50)
lines(t, f2(t,b,lam), col=rgb(180/255, 50/255, 213/255))
```






